// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// CumSum
NumericMatrix CumSum(NumericMatrix m);
RcppExport SEXP _PathActMarker_CumSum(SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(CumSum(m));
    return rcpp_result_gen;
END_RCPP
}
// caliES2
double caliES2(const std::vector<double>& ranks, const std::vector<int>& pos);
RcppExport SEXP _PathActMarker_caliES2(SEXP ranksSEXP, SEXP posSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<double>& >::type ranks(ranksSEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type pos(posSEXP);
    rcpp_result_gen = Rcpp::wrap(caliES2(ranks, pos));
    return rcpp_result_gen;
END_RCPP
}
// matrix_density_R
void matrix_density_R(Rcpp::NumericVector t_X, Rcpp::NumericVector t_Y, Rcpp::NumericVector t_R, Rcpp::IntegerVector t_n_density_samples, Rcpp::IntegerVector t_n_test_samples, Rcpp::IntegerVector t_n_genes, Rcpp::IntegerVector t_rnaseq);
RcppExport SEXP _PathActMarker_matrix_density_R(SEXP t_XSEXP, SEXP t_YSEXP, SEXP t_RSEXP, SEXP t_n_density_samplesSEXP, SEXP t_n_test_samplesSEXP, SEXP t_n_genesSEXP, SEXP t_rnaseqSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type t_X(t_XSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type t_Y(t_YSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type t_R(t_RSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type t_n_density_samples(t_n_density_samplesSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type t_n_test_samples(t_n_test_samplesSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type t_n_genes(t_n_genesSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type t_rnaseq(t_rnaseqSEXP);
    matrix_density_R(t_X, t_Y, t_R, t_n_density_samples, t_n_test_samples, t_n_genes, t_rnaseq);
    return R_NilValue;
END_RCPP
}
// ks_matrix_R
void ks_matrix_R(Rcpp::NumericVector t_X, Rcpp::NumericVector t_R, Rcpp::IntegerVector t_sidxs, Rcpp::IntegerVector t_n_genes, Rcpp::IntegerVector t_geneset_idxs, Rcpp::IntegerVector t_n_geneset, Rcpp::NumericVector t_tau, Rcpp::IntegerVector t_n_samples, Rcpp::IntegerVector t_mx_diff, Rcpp::IntegerVector t_abs_rnk);
RcppExport SEXP _PathActMarker_ks_matrix_R(SEXP t_XSEXP, SEXP t_RSEXP, SEXP t_sidxsSEXP, SEXP t_n_genesSEXP, SEXP t_geneset_idxsSEXP, SEXP t_n_genesetSEXP, SEXP t_tauSEXP, SEXP t_n_samplesSEXP, SEXP t_mx_diffSEXP, SEXP t_abs_rnkSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type t_X(t_XSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type t_R(t_RSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type t_sidxs(t_sidxsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type t_n_genes(t_n_genesSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type t_geneset_idxs(t_geneset_idxsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type t_n_geneset(t_n_genesetSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type t_tau(t_tauSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type t_n_samples(t_n_samplesSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type t_mx_diff(t_mx_diffSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type t_abs_rnk(t_abs_rnkSEXP);
    ks_matrix_R(t_X, t_R, t_sidxs, t_n_genes, t_geneset_idxs, t_n_geneset, t_tau, t_n_samples, t_mx_diff, t_abs_rnk);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_PathActMarker_CumSum", (DL_FUNC) &_PathActMarker_CumSum, 1},
    {"_PathActMarker_caliES2", (DL_FUNC) &_PathActMarker_caliES2, 2},
    {"_PathActMarker_matrix_density_R", (DL_FUNC) &_PathActMarker_matrix_density_R, 7},
    {"_PathActMarker_ks_matrix_R", (DL_FUNC) &_PathActMarker_ks_matrix_R, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_PathActMarker(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
