# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CumSum <- function(m) {
    .Call('_PathActMarker_CumSum', PACKAGE = 'PathActMarker', m)
}

caliES2 <- function(ranks, pos) {
    .Call('_PathActMarker_caliES2', PACKAGE = 'PathActMarker', ranks, pos)
}

matrix_density_R <- function(t_X, t_Y, t_R, t_n_density_samples, t_n_test_samples, t_n_genes, t_rnaseq) {
    invisible(.Call('_PathActMarker_matrix_density_R', PACKAGE = 'PathActMarker', t_X, t_Y, t_R, t_n_density_samples, t_n_test_samples, t_n_genes, t_rnaseq))
}

ks_matrix_R <- function(t_X, t_R, t_sidxs, t_n_genes, t_geneset_idxs, t_n_geneset, t_tau, t_n_samples, t_mx_diff, t_abs_rnk) {
    invisible(.Call('_PathActMarker_ks_matrix_R', PACKAGE = 'PathActMarker', t_X, t_R, t_sidxs, t_n_genes, t_geneset_idxs, t_n_geneset, t_tau, t_n_samples, t_mx_diff, t_abs_rnk))
}

